import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {app} from '../src/app.js';
import {prisma} from '../src/config/prisma.js';
import {signAuthToken} from '../src/utils/tokens.js';

test('money accounts: receipts, funding, payments, transfers, corrections and concurrent spending', {skip:process.env.ZERA_INTEGRATION!=='1'},async()=>{
  if(!process.env.DATABASE_URL?.includes(':5548/zera_project_test'))throw new Error('Isolated test database required.');
  const business=await prisma.business.create({data:{name:`Money ${randomUUID()}`,type:'Retail shop',modules:{create:['POS','FINANCE','INVENTORY'].map(key=>({key,active:true}))}}});
  const branch=await prisma.branch.create({data:{businessId:business.id,name:'Main'}});
  const other=await prisma.branch.create({data:{businessId:business.id,name:'Other'}});
  const users=[];
  async function member(name){const role=await prisma.role.create({data:{businessId:business.id,name}});const user=await prisma.user.create({data:{name,email:`${randomUUID()}@test.invalid`,passwordHash:'test-only',memberships:{create:{businessId:business.id,roleId:role.id}}}});users.push(user.id);return user;}
  const owner=await member('Owner'),keeper=await member('Store Keeper');
  const product=await prisma.product.create({data:{businessId:business.id,name:'Test item',price:100}});
  await prisma.inventoryStock.create({data:{businessId:business.id,branchId:branch.id,productId:product.id,quantity:100}});
  const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
  async function call(path,body,user=owner,method=body?'POST':'GET'){
    const response=await fetch(`http://127.0.0.1:${server.address().port}/api${path}`,{method,headers:{Authorization:`Bearer ${signAuthToken(user)}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,data:await response.json()};
  }
  const base=`/money/business/${business.id}`;
  const get=()=>call(`${base}?branchId=${branch.id}`);
  const move=body=>call(`${base}/movements`,{branchId:branch.id,note:'Test reference',requestKey:randomUUID(),...body});
  const sale=paymentMethod=>call('/pos/sales',{businessId:business.id,branchId:branch.id,paymentMethod,requestKey:randomUUID(),items:[{productId:product.id,quantity:1}]});
  const check=(result,status)=>assert.equal(result.status,status,JSON.stringify(result));
  try{
    const oldSale=await sale('CASH');check(oldSale,201);
    assert.equal(await prisma.moneyPosting.count({where:{businessId:business.id}}),0);
    check(await call(`${base}?branchId=${branch.id}`,undefined,keeper),403);
    const opening={branchId:branch.id,opening:{CASH:'1000',BANK:'2000',MOMO:'300'}};
    check(await call(`${base}/start`,opening),201);check(await call(`${base}/start`,opening),409);
    check(await call(`${base}/start`,{branchId:other.id,opening:{CASH:'100'}}),201);
    let snapshot=(await get()).data;
    const account=code=>snapshot.accounts.find(item=>item.code===code).id;
    assert.equal(Number(snapshot.accounts.find(item=>item.code==='CASH').balance),1000,'Historical sales must not be added to opening balances');
    const cashSale=await sale('CASH');check(cashSale,201);check(await sale('MOBILE_MONEY'),201);check(await sale('CARD'),201);
    snapshot=(await get()).data;
    assert.equal(Number(snapshot.accounts.find(item=>item.code==='CASH').balance),1100);
    assert.equal(Number(snapshot.accounts.find(item=>item.code==='MOMO').balance),400);
    assert.equal(Number(snapshot.accounts.find(item=>item.code==='BANK').balance),2000);
    assert.equal(Number(snapshot.accounts.find(item=>item.code==='CARD_CLEARING').balance),100);
    const transferBody={kind:'TRANSFER',fromAccountId:account('CASH'),toAccountId:account('BANK'),amount:'200',requestKey:randomUUID()};
    const transfers=await Promise.all([move(transferBody),move(transferBody)]);transfers.forEach(result=>check(result,201));assert.equal(transfers[0].data.posting.id,transfers[1].data.posting.id);
    check(await move({...transferBody,amount:'201'}),409);
    check(await move({kind:'LOAN',toAccountId:account('MOMO'),amount:'500'}),201);
    check(await move({kind:'TRANSFER',fromAccountId:account('CARD_CLEARING'),toAccountId:account('BANK'),amount:'100'}),201);
    const expense=await prisma.expense.create({data:{businessId:business.id,branchId:branch.id,title:'Rent',category:'Rent',amount:2000,status:'APPROVED',recordedById:owner.id}});
    const paid=await move({kind:'EXPENSE',sourceId:expense.id,fromAccountId:account('CASH'),amount:'100',note:'=SUM(1,2)'});check(paid,201);
    check(await call(`/finance/business/${business.id}/expenses/${expense.id}/status`,{status:'REJECTED'},owner,'PATCH'),409);
    const supplier=await prisma.supplier.create({data:{businessId:business.id,name:'Supplier'}});
    const purchase=await prisma.purchaseOrder.create({data:{businessId:business.id,branchId:branch.id,supplierId:supplier.id,createdById:owner.id,number:randomUUID(),currency:'UGX',status:'ORDERED',total:600}});
    check(await move({kind:'PURCHASE',sourceId:purchase.id,fromAccountId:account('BANK'),amount:'400'}),201);
    check(await move({kind:'PURCHASE',sourceId:purchase.id,fromAccountId:account('BANK'),amount:'201'}),409);
    check(await call(`/purchasing/business/${business.id}/orders/${purchase.id}/cancel`,{}),409);
    const otherAccount=await prisma.moneyAccount.findUnique({where:{branchId_code:{branchId:other.id,code:'CASH'}}});
    check(await move({kind:'EXPENSE',sourceId:expense.id,fromAccountId:otherAccount.id,amount:'1'}),400);
    const raced=await Promise.all([1,2].map(()=>move({kind:'EXPENSE',sourceId:expense.id,fromAccountId:account('CASH'),amount:'600'})));
    assert.deepEqual(raced.map(item=>item.status).sort(),[201,409]);
    check(await call(`${base}/postings/${paid.data.posting.id}/reverse`,{note:'Wrong expense account'}),200);
    check(await call(`${base}/postings/${paid.data.posting.id}/reverse`,{note:'Retry'}),200);
    check(await call(`/pos/sales/business/${business.id}/${cashSale.data.sale.id}/void`,{reason:'Test refund'},owner,'PATCH'),200);
    snapshot=(await get()).data;
    assert.equal(Number(snapshot.accounts.find(item=>item.code==='CASH').balance),200);
    assert.equal(Number(snapshot.accounts.find(item=>item.code==='BANK').balance),1900);
    assert.equal(Number(snapshot.accounts.find(item=>item.code==='MOMO').balance),900);
    assert.equal(snapshot.documents.find(item=>item.id===purchase.id).outstanding,'200.00');
    assert.equal(snapshot.documents.find(item=>item.id===expense.id).outstanding,'1400.00');
    check(await call(`/pos/sales/business/${business.id}/${oldSale.data.sale.id}/void`,{reason:'Pre-tracking refund'},owner,'PATCH'),200);
    assert.equal(Number((await get()).data.accounts.find(item=>item.code==='CASH').balance),100);
    const all=await prisma.moneyPosting.findMany({where:{businessId:business.id},include:{entries:true}});
    for(const posting of all)assert.equal(posting.entries.reduce((sum,line)=>sum+Number(line.amount),0),0,'Each posting balances');
    const filtered=await call(`${base}?branchId=${branch.id}&accountId=${account('BANK')}`);check(filtered,200);
    assert.ok(filtered.data.postings.length>0);
    assert.ok(filtered.data.postings.every(item=>item.entries.some(entry=>entry.accountId===account('BANK'))));
    assert.equal(filtered.data.total,all.filter(item=>item.branchId===branch.id&&item.entries.some(entry=>entry.accountId===account('BANK'))).length);
    assert.equal(filtered.data.accounts.find(item=>item.code==='CASH').balance,'100.00','History filters must not change balances');
    check(await call(`${base}?branchId=${branch.id}&accountId=${otherAccount.id}`),400);
    const cashHistory=await call(`${base}?branchId=${branch.id}&accountId=${account('CASH')}`);
    assert.ok(cashHistory.data.postings.find(item=>item.id===paid.data.posting.id)?.correctedById,'Corrected status must be returned even when reversal is a separate row');
    const exported=await fetch(`http://127.0.0.1:${server.address().port}/api${base}/export?branchId=${branch.id}&accountId=${account('CASH')}`,{headers:{Authorization:`Bearer ${signAuthToken(owner)}`}});
    assert.equal(exported.status,200);assert.match(exported.headers.get('content-type'),/text\/csv/);
    const csv=await exported.text();assert.match(csv,/Money in/);assert.ok(csv.includes(paid.data.posting.id));assert.ok(csv.includes("\"'=SUM(1,2)\""),'Spreadsheet formulas must be escaped');assert.ok(!csv.includes('"Bank"'));
    assert.equal(csv.trim().split('\r\n').length,all.filter(item=>item.branchId===branch.id).flatMap(item=>item.entries).filter(entry=>entry.accountId===account('CASH')).length+1,'Export includes all matching entries, not one history page');
    check(await call(`${base}/export?branchId=${branch.id}`,undefined,keeper),403);
    check(await call(`${base}/export?branchId=${branch.id}&accountId=${otherAccount.id}`),400);
    const snapshotAgain=await get();check(snapshotAgain,200);assert.equal(snapshotAgain.data.postings.length,10);
    const expenseRequest={title:'Delivery',category:'Transport',branchId:branch.id,amount:'10',note:'',requestKey:randomUUID()};
    const submitted=await Promise.all([1,2].map(()=>call(`/finance/business/${business.id}/expenses`,expenseRequest,keeper)));
    submitted.forEach(r=>check(r,201));assert.equal(submitted[0].data.expense.id,submitted[1].data.expense.id);
    check(await call(`/finance/business/${business.id}/expenses`,{...expenseRequest,amount:'11'},keeper),409);
    check(await call(`/finance/business/${business.id}/expenses/${submitted[0].data.expense.id}`,{title:'Delivery corrected',category:'Transport',amount:'12',note:''},keeper,'PATCH'),200);
    const payrollBase=`/payroll/business/${business.id}`;
    check(await call(`${payrollBase}?period=2026-10`,undefined,keeper),403);
    check(await call(`${payrollBase}/profiles/${keeper.id}`,{branchId:branch.id,monthlyAmount:'50',active:true},owner,'PUT'),200);
    check(await call(`${payrollBase}/profiles/${randomUUID()}`,{branchId:branch.id,monthlyAmount:'50',active:true},owner,'PUT'),400);
    check(await call(`${payrollBase}/process`,{period:'bad'}),400);
    const prepared=await call(`${payrollBase}/process`,{period:'2026-10'});check(prepared,201);assert.equal(prepared.data.created,1);
    assert.equal((await call(`${payrollBase}/process`,{period:'2026-10'})).data.created,0);
    const payroll=(await call(`${payrollBase}?period=2026-10`)).data;
    const salary=payroll.entries[0].expense;assert.equal(salary.category,'Salary');assert.equal(salary.status,'PENDING');
    check(await move({kind:'EXPENSE',sourceId:salary.id,fromAccountId:account('CASH'),amount:'50'}),409);
    check(await call(`/finance/business/${business.id}/expenses/${salary.id}`,{title:salary.title,category:'Salary',amount:'60',note:'Adjusted salary'},owner,'PATCH'),200);
    check(await call(`/finance/business/${business.id}/expenses/${salary.id}/status`,{status:'APPROVED'},owner,'PATCH'),200);
    check(await call(`/finance/business/${business.id}/expenses/${salary.id}`,{title:salary.title,category:'Salary',amount:'70',note:''},owner,'PATCH'),409);
    check(await move({kind:'EXPENSE',sourceId:salary.id,fromAccountId:account('CASH'),amount:'60'}),201);
    assert.equal((await call(`${payrollBase}?period=2026-10`)).data.entries[0].paid,'60.00');
    const audit=await call(`/finance/business/${business.id}/expenses/${salary.id}/history`);check(audit,200);assert.ok(audit.data.events.some(e=>e.action==='EXPENSE_EDITED'));
    check(await call(`/finance/business/${business.id}/expenses/${salary.id}/history`,undefined,keeper),404);
    check(await move({kind:'WITHDRAWAL',fromAccountId:account('CASH'),amount:'20'}),201);
    check(await move({kind:'WITHDRAWAL',fromAccountId:account('CASH'),amount:'21'}),409);
    const cashflow=await call(`/finance/business/${business.id}/cashflow?branchId=${branch.id}`);check(cashflow,200);
    assert.equal(cashflow.data.accounts.find(a=>a.name==='Cash').balance,'20.00');
    assert.equal(cashflow.data.movements.find(m=>m.kind==='WITHDRAWAL').amount,'20.00');
    check(await call(`/finance/business/${business.id}/cashflow`,undefined,keeper),403);
    const searched=await call(`/finance/business/${business.id}/expenses?search=Salary&status=APPROVED`);check(searched,200);assert.equal(searched.data.expenses.length,1);assert.equal(searched.data.expenses[0].paid,'60.00');
    assert.deepEqual(cashflow.data.tracking,{branches:1,tracked:1});
    assert.equal(cashflow.data.accounts.find(a=>a.name==='Cash').code,'CASH');
    const future=await call(`${base}?branchId=${branch.id}&dateFrom=2099-01-01&dateTo=2099-01-31`);check(future,200);assert.equal(future.data.total,0);assert.equal(future.data.accounts.find(a=>a.code==='CASH').balance,'20.00');
    check(await call(`${base}?branchId=${branch.id}&dateFrom=2026-10-10&dateTo=2026-10-01`),400);
    const searchedHistory=await call(`${base}?branchId=${branch.id}&search=${paid.data.posting.id}`);check(searchedHistory,200);assert.equal(searchedHistory.data.total,1);
    const exportFuture=await fetch(`http://127.0.0.1:${server.address().port}/api${base}/export?branchId=${branch.id}&dateFrom=2099-01-01`,{headers:{Authorization:`Bearer ${signAuthToken(owner)}`}});assert.equal(exportFuture.status,200);assert.equal((await exportFuture.text()).trim().split('\r\n').length,1,'Filtered export must match filtered history');
    const futureFlow=await call(`/finance/business/${business.id}/cashflow?branchId=${branch.id}&dateFrom=2099-01-01`);check(futureFlow,200);assert.equal(futureFlow.data.movements.length,0);assert.equal(futureFlow.data.accounts.find(a=>a.name==='Cash').balance,'20.00');
    const paymentView=await call(`${base}?branchId=${branch.id}&view=payments`);check(paymentView,200);assert.ok(paymentView.data.postings.every(p=>['EXPENSE','PURCHASE'].includes(p.kind)));
    const incomeView=await call(`${base}?branchId=${branch.id}&view=income`);check(incomeView,200);assert.ok(incomeView.data.postings.every(p=>['SALE','CAPITAL','LOAN','OTHER_INCOME'].includes(p.kind)));
  }finally{
    await new Promise(resolve=>server.close(resolve));
    await prisma.payrollEntry.deleteMany({where:{businessId:business.id}});
    await prisma.salaryProfile.deleteMany({where:{businessId:business.id}});
    await prisma.moneyEntry.deleteMany({where:{posting:{businessId:business.id}}});
    await prisma.moneyPosting.deleteMany({where:{businessId:business.id}});
    await prisma.moneyAccount.deleteMany({where:{businessId:business.id}});
    await prisma.saleItem.deleteMany({where:{sale:{businessId:business.id}}});
    await prisma.business.delete({where:{id:business.id}});
    await prisma.user.deleteMany({where:{id:{in:users}}});await prisma.$disconnect();
  }
});
