import { Search, ReceiptText } from 'lucide-react';

const examples = {
  restaurant: { heading:'Menu entry', customer:'Table 04 · Walk-in customer', cart:'Table order', action:'Send table order', products:[['Grilled chicken',25000],['Fresh juice',8000],['Vegetable rice',15000],['House coffee',6000],['Bottled water',3000],['Soft drink',4000]], steps:['Choose table','Add order','Cashier closes bill'] },
  hotel: { heading:'Guest service entry', customer:'Guest / customer · Walk-in guest', cart:'Guest charges', action:'Review service sale', products:[['Laundry service',20000],['Airport transfer',80000],['Breakfast',25000],['Room service delivery',5000],['Bottled water',3000],['Late checkout service',50000]], steps:['Choose guest','Add service','Record payment'] },
  pharmacy: { heading:'Medicine and service entry', customer:'Patient / customer · Walk-in customer', cart:'Customer sale', action:'Review pharmacy sale', products:[['First-aid kit',35000],['Digital thermometer',18000],['Adhesive dressings',6000],['Gauze pack',5000],['Hand sanitiser',10000],['Face masks',4000]], steps:['Find item','Confirm quantity','Record payment'] },
  supermarket: { heading:'Scan or search items', customer:'Walk-in customer', cart:'Basket', action:'Review basket sale', products:[['Rice · 1 kg',6000],['Milk · 1 litre',4000],['Bread',5000],['Cooking oil · 1 litre',12000],['Sugar · 1 kg',5000],['Laundry soap',4000]], steps:['Scan or search','Build basket','Record payment'] },
};
const money = value => value.toLocaleString('en-UG');
export default function CheckoutPreview({kind}) {
  const example=examples[kind];
  return <><div className="tour-flow">{example.steps.map((step,index)=><span key={step}><b>{index+1}</b>{step}</span>)}</div>{kind==='restaurant'&&<div className="tour-tables" aria-label="Example table selection"><span>Table 01<small>Available</small></span><span className="selected">Table 04<small>Selected · Open order</small></span><span>Table 06<small>Awaiting payment</small></span></div>}<div className="tour-pos"><section className="tour-card"><h3>{example.heading}</h3><div className="tour-search"><Search size={14}/>{kind==='hotel'?'Search services or charges':kind==='restaurant'?'Search menu items':'Search product, SKU, or barcode'}</div><div className="tour-products">{example.products.map(([name,price])=><div key={name}><strong>{name}</strong><span>UGX {money(price)}</span></div>)}</div><div className="tour-pagination">1–6 of 6<span>Page 1 of 1</span></div></section><section className="tour-card tour-cart"><h3>{example.cart}</h3><small>{example.customer}</small>{example.products.slice(0,2).map(([name,price])=><div className="tour-cart-line" key={name}><strong>{name}</strong><span>1 × {money(price)}</span></div>)}<div className="tour-total"><span>Total</span><strong>UGX {money(example.products[0][1]+example.products[1][1])}</strong></div>{kind==='restaurant'?<p className="tour-handoff">The waiter sends the order. The cashier receives payment and closes the bill.</p>:<><small>Payment method</small><div className="tour-payment">Cash</div></>}<div className="tour-action"><ReceiptText size={14}/>{example.action}</div></section></div></>;
}
