import {useEffect,useState,useRef} from 'react';
import {api} from '../../services/api.js';
import {useWorkspace} from '../../context/WorkspaceContext.jsx';
import {Link} from 'react-router-dom';
import Button from '../../components/Button.jsx';
import Pagination,{usePagination} from '../../components/Pagination.jsx';
import FinanceNav from './FinanceNav.jsx';
const field='mt-1 block w-full rounded border border-zera-line p-2';
export default function PayrollPage(){const {activeBusinessId,activeBusiness,branches}=useWorkspace();const [period,setPeriod]=useState(new Date().toISOString().slice(0,7)),[data,setData]=useState(null),[form,setForm]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[revision,setRevision]=useState(0);const busy=useRef(false);useEffect(()=>{let cancelled=false;setData(null);setError('');api.get(`/payroll/business/${activeBusinessId}`,{params:{period}}).then(r=>{if(!cancelled)setData(r.data);}).catch(e=>{if(!cancelled)setError(e.response?.data?.message||'Unable to load payroll.');});return()=>{cancelled=true;};},[activeBusinessId,period,revision]);useEffect(()=>{setForm(null);setMessage('');},[activeBusinessId]);const pages=usePagination(data?.entries||[]),profiles=usePagination(data?.profiles||[]);const fmt=v=>`${activeBusiness?.currency} ${Number(v||0).toLocaleString()}`;
 async function save(path,body,method='post'){if(busy.current)return;busy.current=true;setSaving(true);setError('');setMessage('');try{const result=await api[method](`/payroll/business/${activeBusinessId}${path}`,body);setMessage(path==='/process'?`${result.data.created} salary expenses created. Review them in Expenses.`:'Salary saved.');setForm(null);setRevision(v=>v+1);}catch(e){setError(e.response?.data?.message||'Unable to save payroll.');}finally{busy.current=false;setSaving(false);}}
 return <div className="mx-auto max-w-[1500px] space-y-5"><FinanceNav/><header className="flex flex-wrap justify-between gap-3"><h2 className="text-2xl font-bold">Payroll</h2><Button disabled={saving} onClick={()=>setForm({employeeId:'',branchId:'',monthlyAmount:'',active:true})}>Set salary</Button></header>{error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status" className="text-zera-green">{message}</p>}{form&&<form className="space-y-4 rounded-xl border bg-white p-5" onSubmit={e=>{e.preventDefault();save(`/profiles/${form.employeeId}`,form,'put');}}><div className="grid gap-4 sm:grid-cols-3"><label>Team member<select required disabled={saving} className={field} value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}><option value="">Choose employee</option>{data?.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Branch<select required disabled={saving} className={field} value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">Choose branch</option>{branches.filter(b=>b.status==='ACTIVE').map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Monthly amount payable<input required disabled={saving} className={field} type="number" min="0.01" max="9999999999.99" step="0.01" value={form.monthlyAmount} onChange={e=>setForm({...form,monthlyAmount:e.target.value})}/></label></div><label className="flex gap-2"><input disabled={saving} type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Include in monthly payroll</label><p className="text-xs text-zera-muted">Enter the agreed amount payable. Statutory taxes, deductions and benefits are not calculated here.</p><Button disabled={saving} type="submit">Save salary</Button> <Button disabled={saving} variant="secondary" type="button" onClick={()=>setForm(null)}>Cancel</Button></form>}
 <section className="overflow-hidden rounded-xl border bg-white"><h3 className="p-4 font-bold">Employee salaries</h3>{profiles.rows.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-3 border-t p-4"><div><p className="font-semibold">{p.employee.name}</p><p className="text-sm text-zera-muted">{p.branch.name} · {p.active?'Active':'Paused'}</p></div><span>{fmt(p.monthlyAmount)}</span><Button disabled={saving} variant="secondary" onClick={()=>setForm({employeeId:p.employeeId,branchId:p.branchId,monthlyAmount:p.monthlyAmount,active:p.active})}>Edit</Button></div>)}{data&&!data.profiles.length&&<p className="p-4 text-zera-muted">No salaries configured.</p>}<Pagination {...profiles}/></section>
 <section className="overflow-hidden rounded-xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 p-4"><h3 className="font-bold">Monthly payroll</h3><label>Month <input disabled={saving} required type="month" value={period} onChange={e=>{if(e.target.value)setPeriod(e.target.value);}}/></label><Button disabled={saving||!data?.profiles.some(p=>p.active)} onClick={()=>save('/process',{period})}>Prepare salary expenses</Button></div><p className="px-4 pb-3 text-sm text-zera-muted">One entry per employee per month. Review and approve in Expenses, then pay from Payments.</p>{pages.rows.map(row=><div key={row.id} className="flex flex-wrap justify-between gap-3 border-t p-4"><div><p className="font-semibold">{row.expense.title}</p><p className="text-xs text-zera-muted">{row.expense.status}</p></div><div className="text-right"><p>{fmt(row.expense.amount)}</p><p className="text-xs text-zera-muted">Paid {fmt(row.paid)} · Due {fmt(Number(row.expense.amount)-Number(row.paid))}</p></div></div>)}{data&&!data.entries.length&&<p className="p-4 text-zera-muted">No payroll prepared for this month.</p>}<Pagination {...pages}/><div className="flex gap-4 border-t p-4"><Link className="text-zera-green underline" to="/finance/expenses">Review expenses</Link><Link className="text-zera-green underline" to="/finance/payments">Pay approved salaries</Link></div></section></div>;
}
